### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by jm-riley** [joshhk72/prodigy#2]
### `tracks`
- [x] we probably want state to be set up to handle storing multiple tracks at a time, much like how the other entities are set up. if you ever need to display info on multiple tracks at once, such as on an index page or as part of a list, this will be necessary
- [x] you can keep track of the `annotations` for a particular `track` with an array of `annotation_ids`
- [x] array of `comment_ids` for `track`
- [x] `artist_id` on individual tracks
- [x] needs a key of `bio_id`

### `annotations`
- [x] primary key of `id` stored inside of each `annotation` object

### `users`
- [x] `users` slice of state under `entities` to store basic user info 

Let me know if you have any questions or disagree with any of these points and we can discuss. Nice work!

**Comment by joshhk72** [comment]
i think ill use another array for "bio_ids". They call it bio, but it looks like a track/artist/album can have multiple.
